import type { Livre } from "@/lib/types";

// Auteurs & livres de l'édition 2026 — une entrée = une carte.
// Couvertures optimisées dans /images/livres/. Ajoutez `photo` (portrait de
// l'auteur) et `description` quand ils sont fournis.
export const livres: Livre[] = [
  {
    titre: "17 jours dans la fosse aux lions",
    auteur: "Nenel Cassy",
    genre: "Récit politique",
    prix: "1 000 HTG",
    couverture: "/images/livres/17-jours-fosse-aux-lions.jpg",
  },
  {
    titre: "Fais-moi jouir",
    auteur: "Viannye Ménard",
    genre: "Roman",
    prix: "1 300 HTG",
    couverture: "/images/livres/fais-moi-jouir.jpg",
  },
  {
    titre: "Choisir ses études en Haïti",
    auteur: "Stanley Joseph & Djeff Prophil",
    genre: "Essai",
    prix: "1 000 HTG",
    couverture: "/images/livres/choisir-ses-etudes-en-haiti.jpg",
    note: "Préface de Placide Jobby",
  },
  {
    titre: "J'ai combattu le bon combat",
    auteur: "Abraham Edmond",
    genre: "Spiritualité",
    prix: "1 700 HTG",
    couverture: "/images/livres/jai-combattu-le-bon-combat.jpg",
  },
  {
    titre: "La peur des femmes",
    auteur: "Jackson Chéry",
    genre: "Roman",
    prix: "1 200 HTG",
    couverture: "/images/livres/la-peur-des-femmes.jpg",
  },
  {
    titre: "Lanmou Anba Fenèt ak Klere Chimen",
    auteur: "Joseph Jackson",
    genre: "Poésie",
    prix: "1 000 HTG",
    couverture: "/images/livres/lanmou-anba-fenet.jpg",
  },
  {
    titre: "Lascahobas 2054",
    auteur: "Willène Polynice (Madame Popo)",
    genre: "Essai",
    prix: "1 200 HTG",
    couverture: "/images/livres/lascahobas-2054.jpg",
  },
  {
    titre: "Le code de la prospérité",
    auteur: "Rev. Clausel Cadet",
    genre: "Développement personnel",
    prix: "2 000 HTG",
    couverture: "/images/livres/le-code-de-la-prosperite.jpg",
  },
  {
    titre: "Le début d'une scène",
    auteur: "Ginifred V. Marcelin",
    genre: "Roman",
    prix: "1 500 HTG",
    couverture: "/images/livres/le-debut-dune-scene.jpg",
  },
  {
    titre: "Les hésitations de la passion",
    auteur: "Dimitri Norris",
    genre: "Roman",
    prix: "2 000 HTG",
    couverture: "/images/livres/les-hesitations-de-la-passion.jpg",
  },
  {
    titre: "Les liens du destin",
    auteur: "Wendy Clara Jn Baptiste",
    genre: "Roman",
    prix: "1 000 HTG",
    couverture: "/images/livres/les-liens-du-destin.jpg",
  },
  {
    titre: "Mirak resèt ak te lakay",
    auteur: "Jean Hector Anacacis",
    genre: "Santé & bien-être",
    prix: "4 000 HTG",
    couverture: "/images/livres/mirak-reset-ak-te-lakay.jpg",
  },
  {
    titre: "Collection de réflexions certaines pour construire une vie chrétienne triomphante",
    auteur: "Kelly Baldé, D.D. & Ph.D.",
    genre: "Spiritualité",
    prix: "2 500 HTG",
    couverture: "/images/livres/reflexions-vie-chretienne.jpg",
    note: "Réflexions de 2016 à 2024",
  },
  {
    titre: "Soulèvement général des poussières",
    auteur: "Jean Lesly Cérome",
    genre: "Poésie",
    prix: "1 000 HTG",
    couverture: "/images/livres/soulevement-general-des-poussieres.jpg",
  },
  {
    titre: "Tourner la page",
    auteur: "Nènel Cassy",
    genre: "Essai",
    prix: "1 500 HTG",
    couverture: "/images/livres/tourner-la-page.jpg",
    note: "Haïti au carrefour du développement",
  },
  {
    titre: "Tralala",
    auteur: "Joseph Jackson",
    genre: "Poésie",
    prix: "1 000 HTG",
    couverture: "/images/livres/tralala.jpg",
    note: "Limyè anviwònman latè tenyen",
  },
];
